### ISSUE TITLE
Problem with the Opinion page chart and formatting

### ISSUE THREAD

**Issue by JohnSmith-LT** [thexerteproject/xerteonlinetoolkits#1104]
Is it my imagination or are there a few problems with the Opinion page (that I've never noticed before) @ronm123 @FayCross ?

This demo asks 11 questions:

![image](https://user-images.githubusercontent.com/3907362/171463889-d70a286a-a7e7-47de-8d23-c636f3a67141.png)

But the first Question text is centred (or at least an attempt has been made to centre it - it's slightly off) and the rest (although they have "text-align: centre" style added) are not centred - I think I prefer the left justified version anyway but just wondering if this is new?

Also the chart, although it displays with the correct selections, it is showing the Page Title as the popup for every question's results:

![image](https://user-images.githubusercontent.com/3907362/171464504-8219bb2d-0552-4751-9b0b-d1a3beb918e9.png)

Should this not be the actual Question text? Or am I just being a bit dense?

Also do we think that the numeric parts should display a % sign afterwards?

**Comment by JohnSmith-LT** [comment]
Seems that qTxt class was being applied to the question holder but no style had been setup. The questions were not centre-ing  because the 'center' style had been added in the editor to the <p> tags but they weren't expanding to full width...

These two bugs are present here too @ronm123 - not sure how long they have been like that...

https://xot.xerte.org.uk/play.php?template_id=81#v3.6section22

Now the chart shows like this:

![image](https://user-images.githubusercontent.com/3907362/171506187-2d4c2eb9-a27c-4eee-9109-e761624fa50e.png)

**Comment by JohnSmith-LT** [comment]
Messed up the commit tagging https://github.com/thexerteproject/xerteonlinetoolkits/commit/f97044449739c913f8a5a7e2ecfd19149ad488e8

**Comment by ronm123** [comment]
@JohnSmith-LT that LO is embedded from one of my installations and I just checked it...
There's no relevant custom css applied and the labels e.g. New Themes are just plain text inputs so no alignment styling applied there. Not sure why the first label isn't aligned left like the others but it's obviously not centred either.
Re the question results in the chart not showing the labels - that seems like a bug must have crept in at some point after we used this. I'm sure @torinfo will know?
Can't remember if we've got a test project on any of the installs Tom looks after with shared access that we can use as a reference for this?

**Comment by JohnSmith-LT** [comment]
Hi @ronm123 both those things are now fixed in develop

The Question titles were centred using the Editor but the container was collapsing to minimum size - i've expanded the container to 100% and now the titles all work centred.

**Comment by ronm123** [comment]
@JohnSmith-LT I put your changed model and css file in place in my install from where the LO is embedded and initially I could see the labels on the chart on hover were now correct. However then I couldn't see the LO at all so I put the older model and css in place but still not working. I'm probably missing something and I doubt this is due to your commits here. Will email you and @torinfo with further details.

**Comment by ronm123** [comment]
@JohnSmith-LT @torinfo sorry rushing this and probably doing something stupid :-( Or possibly just caching. My install where this is embedded from is now latest develop and as you say John the titles are now all centred. Also because my install is now develop you'll see that on the release notes page we now get the play button that you have to click before the LO is available.
@torinfo is better placed to advise whether this issue should now be closed.

**Comment by ronm123** [comment]
@JohnSmith-LT @torinfo BTW in testing this and getting what was probably just caching issues and because I had the console open I was getting a pause with a call to debugger somewhere but can't replicate that now.

**Comment by JohnSmith-LT** [comment]
@ronm123 I checked that link again and your LO isn't loading because it cannot find loadjs. You will need to pull down the latest xenith.js file also as loadjs has been added to better handle dependency loading and catch missing files which the previous $script loader couldn't do.

**Comment by ronm123** [comment]
@JohnSmith-LT it's loading for me. Do you not see the LO with the big white play icon overlay? I updated my install to latest develop so it should have all the files and that was over 4 hours ago. Caching at your end?

**Comment by JohnSmith-LT** [comment]
Yes @ronm123, was caching. I don't get a debugger pause so not sure what that was...

**Comment by FayCross** [comment]
@JohnSmith-LT looks like you & @ronm123 have sorted some of this out now. I haven't used the opinion page so probably aren't best placed to comment on how it works but above you asked 'do we think that the numeric parts should display a % sign afterwards?' and yes, I think that would make more sense.

**Comment by FayCross** [comment]
Can the numbers on the graph be made bigger? They are so small in an example I just made that I didn't realise they were numbers and was looking for an option in editor to turn the numbers on

**Comment by JohnSmith-LT** [comment]
@FayCross tbh I haven't used this much either and th results page that @torinfo has for tracking exhibits the same strange sizing of numbers and the chart...

I think at some point in the future we cold revisit charting in all the pages and upgrade to a more modern and compliant library which may improve accessibility for these colour and graphic heavy pages...

I'm going to close this for now but please reopen if anyone has concerns about any of this for the current release.
