### ISSUE TITLE
Matching texts page type issues?

### ISSUE THREAD

**Issue by ronm123** [thexerteproject/xerteonlinetoolkits#551]
Hi all
I had a report that projects with a matching texts page created in previous versions were no longer working in 3.3. I've tried to have a look at this but in fact if I create a new xot project using current develop code and just add a matching text page and then 3 sentences without actually changing the default sentences the project doesn't display at all. If I then edit those defaults in each of the sentences the project plays.

I created a test project in a 2.x install and imported that into 3.3 and the same thing applies e.g. if the default sentence isn't changed the page doesn't play but once the default sentences are changed the project plays.

Anyone else able to replicate this? Are all of your existing projects with this page type created before 3.3 still working in 3.3?

**Comment by ronm123** [comment]
Just to add after investigating further on a real project...
The real project exists and works in a 3.1 install but after upgrading a copy of that installation to 3.3 that same project and the matching texts pages it contains no longer plays those pages. If I then edit the sentences in those pages e.g. remove last letter and then re-add the last letter I can get the pages working again. But obviously we don't want to force users to have to do that.

It's easy to replicate...
1. Create a new project in 3.3 or latest develop
2. Add a matching texts page and 3 sentences without editing anything
3. Play the project and view in browser console
You should see something like:
jquery-1.9.1.min.js:4 Uncaught Error: Syntax error, unrecognized expression: Write part one of your sentence here.
4. Edit the sentences
5. Play the project and all should be fine
Anyone recognise what's changed to cause this and of course how to fix it?

**Comment by torinfo** [comment]
I fixed this (See #548)

I also published a hotfix for this.

**Comment by torinfo** [comment]
Oops, that wasn't Matching Text but Matching pairs. Apologies. Will have a look.

**Comment by ronm123** [comment]
Hi all
I've been working through a reported issue that at first I couldn't replicate but it seems it only happens under specific circumstances and even then seems like it isn't consistent. Here's a few notes and screenshots:
Using latest develop create a new project and add a matching texts page
Add 4 or more matching texts
Add any page type after that page so that you can navigate away and then back again
Make the project public and view the play url
Interact with the matching text page and get all the answers correct and submit
navigate to the next page and then back again
On at least some occasions when navigating back the page will look like the following:
![image](https://cloud.githubusercontent.com/assets/5167146/20220869/199aa954-a827-11e6-9318-ec15d59b2aed.png)

That said if you refresh and repeat the interaction then navigate away and then back some times it will work as it should and you then have to refresh and repeat again to get it to show the problem and also if instead of getting it 100% correct you get some wrong I've also noticed it show only 3 or 2 of the sentences and targets upon return e.g.
![image](https://cloud.githubusercontent.com/assets/5167146/20220987/84e75590-a827-11e6-8244-59c0b968bb0e.png)

For reference this is what my test file consists of:
![image](https://cloud.githubusercontent.com/assets/5167146/20221001/9940d9ee-a827-11e6-9fa5-f4db81f80d24.png)

My test is with 3.3 and latest develop. Can you replicate? I'm not sure how to identify the cause or correct this especially given the intermittent nature of it.

**Comment by FayCross** [comment]
Yes, I can see this Ron. It seems to be a problem with the new tracking stuff added to the page. If I comment out the contents of the finishTracking function it works fine. Any chance you could have a look @torinfo ? I don't want to break the tracking and I don't know how to best test this would still be working.

Thanks

**Comment by FayCross** [comment]
Oh, and I also found another bug on this page which is fixed if the tracking is removed:

Add a few sentences and preview.
Drag and drop one label into place.
Move to next page & back again.
The labels will have reset correctly but the sentence you dragged the label to will have disappeared (e.g. there will now be 3 labels but only 2 sentences)

**Comment by ronm123** [comment]
@FayCross @torinfo I've been testing this again so a few comments...

@FayCross yes I also noticed that different behaviour which was my second screenshot above e.g. "also if instead of getting it 100% correct you get some wrong I've also noticed it show only 3 or 2 of the sentences and targets upon return"

So I've been testing again with the same test file I set up previously but this time also tested with Firefox, IE11, Edge and Opera as well as Chrome. I could only replicate the issue in Chrome not in the other browsers. So then I cleared cache in Chrome (sure I did that before too) and now I can't replicate in Chrome either.

Does clearing cache resolve the issue for you too? Or are you getting the issue with more than just Chrome anyway?

**Comment by FayCross** [comment]
No, I still see the issue in Chrome, IE11 & Firefox (& sorry I overlooked your 2nd lot of screen shots - that is the same thing I see too)

**Comment by ronm123** [comment]
Sorry my mistake. I'd tested what you said by commenting out the finishTracking function but then thought I'd undone that change but just checked for modifications and the change was still showing. So I've ensured that the files is identical to develop and can now replicate the issue in all browsers.
I can't however spot why the finishTracking function is causing this problem.

Are there syntax issues in that function? e.g. 361, 366 missing , or ;? 
Not sure that's the cause of the problem but just wondering.

Hopefully @torinfo can have a look at this issue.
